Fix realtime telemetry
akhenry/openmct-yamcs pull request #146
Opened 2022-06-13 21:56 UTC by akhenry

Closes #144

### Describe your changes:
* Restores the previous realtime-telemetry-provider which is battle-hardened and known to handle WebSocket dropouts reliably. 
* Refactors the realtime-fault-provider to make use of the realtime-telemetryprovider.

### All Submissions:

* [ ] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [ ] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [ ] Changes address original issue?
* [ ] Unit tests included and/or updated with changes?
* [ ] Command line build passes?
* [ ] Has this been smoke tested?
* [ ] Testing instructions included in associated issue?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate unit tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Commit messages meet standards?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

2022-06-14 19:49 UTC, jvigliotta requested changes
Lookin nice! Lot's of cool stuff in this. Seems pretty rock solid. Just had a couple suggestions and questions, nothing major.

2022-06-14 19:49 UTC, jvigliotta commented on src/providers/realtime-provider.js
> +        }, FALLBACK_AND_WAIT_MS[this.currentWaitIndex]);
This is cool!

2022-06-14 19:49 UTC, jvigliotta commented on src/providers/realtime-provider.js
> +                this.reconnect();
Do we need to return false here? I see you're returning true above. Is anything relying on this? I didn't see anything, if that's true, you may be able to remove that `return true` above.

2022-06-14 19:49 UTC, jvigliotta commented on src/providers/realtime-provider.js
> +        this.socket = new WebSocket(wsUrl);
I know we're overwriting this here, but do we need to set to undefined or anything first? I know we have listeners attached, I think they get removed on error or close, but just checking.

2022-06-14 19:49 UTC, jvigliotta commented on src/providers/realtime-provider.js
> +            try {
Cool use of filter here.

2022-06-15 16:18 UTC, akhenry commented
@jvigliotta I believe I have addressed all of these comments, but due to what appears to be a GitHub bug all of my comments are stuck in a `pending` state.

2022-06-15 20:16 UTC, merged