[Staleness Provider] Using correct property for timestamp and making sure there is a response before acting on it
akhenry/openmct-yamcs pull request #273
Opened 2023-01-27 00:44 UTC by jvigliotta

Closes #272

### Describe your changes:

Couple of fixes here. Using the correct property for getting the timestamp and makings sure there is a response before acting on it.

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [ ] Tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Reviewer has tested changes by following the provided instructions?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

2023-01-30 22:33 UTC, davetsay commented
@jvigliotta , to determine target for this issue

2023-01-30 22:36 UTC, ozyx requested changes
One tiny typo to fix but otherwise this LGTM

2023-01-31 20:23 UTC, jvigliotta commented on src/providers/staleness-provider.js
>          const stalenesObject = buildStalenessResponseObject(
haha, this is NOT the first time I've made that typo...

2023-01-31 20:29 UTC, ozyx approved these changes

2023-01-31 20:29 UTC, merged