Improve LAD and min-max request handing #3
akhenry/openmct-yamcs pull request #28
Opened 2020-11-04 18:15 UTC by nikhilmandlik

### Resolves: 
closes #3 

### Author Checklist:
Check | Passed
-- | --
Changes address original issue? | Y
Unit tests included and/or updated with changes? | N/A
Command line build passes? | Y
Changes have been smoke-tested? | Y
Testing instructions included? | Y

2020-11-10 19:11 UTC, jvigliotta commented on src/providers/historical-telemetry-provider.js
> +    getHistory(id, start, end, size=300, strategy) {
We're getting a lot of parameters at this point along with some defaults, would an "options" paramter work here?

2020-11-10 19:13 UTC, jvigliotta commented on src/providers/historical-telemetry-provider.js
> +        let convertHistory = (res) => this.convertPointHistory(id, res);
Nice!

2020-11-10 19:14 UTC, jvigliotta reviewed
Looking good man, looks a lot cleaner. I like that you handled both sample and regular in one. Just had one comment, may not be anything, but wanted to see what you thought. Ultimately I believe @akhenry will be the final call on this one.

2020-11-10 19:15 UTC, jvigliotta commented on src/providers/historical-telemetry-provider.js
> +        let convertHistory = (res) => this.convertPointHistory(id, res);
I like the use of convertHistory to hold either function.

2021-02-03 19:39 UTC, akhenry requested changes
Blocking merge so I can take a look

2021-02-06 01:27 UTC, akhenry requested changes
This looks great, thanks @nikhilmandlik ! Just one *tiny* thing :) Thanks!

2021-02-06 01:27 UTC, akhenry commented on src/providers/historical-telemetry-provider.js
> +            order = 'desc'
👍 Good catch

2021-02-06 01:27 UTC, akhenry commented on src/providers/historical-telemetry-provider.js
>          url += '&stop=' + (new Date(end).toISOString());
Let's use template strings for the rest of this URL as well, just to be consistent.

2021-02-13 00:06 UTC, akhenry commented
@nikhilmandlik  Conflict, otherwise it's good to merge. Thanks!

2021-02-13 00:12 UTC, merged