Add abort signal for YAMCS search
akhenry/openmct-yamcs pull request #289
Opened 2023-03-10 07:43 UTC by scottbell

Closes #288 

### Describe your changes:
Add passed abort signal to the MDB fetch.

### All Submissions:

* [ ] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [ ] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [ ] Changes address original issue?
* [ ] Tests included and/or updated with changes?
* [ ] Command line build passes?
* [ ] Has this been smoke tested?
* [ ] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Reviewer has tested changes by following the provided instructions?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

2023-03-10 07:51 UTC, scottbell commented
Here's an example of the search requests in action:

https://user-images.githubusercontent.com/9853862/224254324-a463e5cd-352a-4d96-8395-c10056ad34c0.mov

2023-03-14 19:15 UTC, ozyx requested changes
Looks good! Just one debug statement in the e2e that I believe we need to remove?

2023-03-14 19:15 UTC, ozyx commented on tests/e2e/yamcs/network.e2e.spec.js
> +        await page.pause();
We should remove this, right?

2023-03-14 19:48 UTC, ozyx approved these changes
LGTM

2023-03-14 19:48 UTC, merged