Command history inplace updates
akhenry/openmct-yamcs pull request #323
Opened 2023-05-25 22:50 UTC by shefalijoshi

Closes #315 

### Describe your changes:
Rather than create a new view provider and view for command history in openmct-yamcs, added a configuration that indicates that datum for a given object should be updated in place.
Added a unique id for datum that should be aggregated called `messageId`. This will be used by open mct to update data in place for that message/record.

### All Submissions:

* [ ] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [ ] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [ ] Changes address original issue?
* [ ] Tests included and/or updated with changes?
* [ ] Command line build passes?
* [ ] Has this been smoke tested?
* [ ] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Reviewer has tested changes by following the provided instructions?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

2023-06-12 21:24 UTC, ozyx requested changes
Stumbled upon a mistaken version update

2023-06-12 21:24 UTC, ozyx commented on package.json
> +  "version": "2.2.3",
Accidental version modification here

2023-07-11 23:14 UTC, akhenry requested changes
Looks good, thanks. Some small changes suggested on https://github.com/nasa/openmct/pull/6694#discussion_r1260370375 which has implications for this PR.

2023-07-14 23:37 UTC, akhenry approved these changes

2023-07-14 23:38 UTC, ozyx approved these changes

2023-07-15 00:10 UTC, merged