Fix openmct yamcs build and tests
akhenry/openmct-yamcs pull request #410
Opened 2024-01-12 17:47 UTC by shefalijoshi

Closes 

### Describe your changes:

### All Submissions:

* [ ] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [ ] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [ ] Changes address original issue?
* [ ] Tests included and/or updated with changes?
* [ ] Command line build passes?
* [ ] Has this been smoke tested?
* [ ] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Reviewer has tested changes by following the provided instructions?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

2024-01-12 17:49 UTC, unlikelyzero commented on tests/e2e/yamcs/search.e2e.spec.js
> +        await expect(page.getByLabel('Object Search Result').nth(0)).toContainText("CCSDS_Packet_Sequence");
test fixes to match 3.3.0

2024-01-12 18:47 UTC, scottbell reviewed
Tested this in my branch, and code is good, but still looks like some tests are still failing?

2024-01-12 21:29 UTC, unlikelyzero approved these changes

2024-01-13 01:05 UTC, ozyx submitted a review, later dismissed
We can't merge this until we know consumers can still import it. I tested this with VIPER and it's totally borked, so likely (possibly?) a webpack configuration or something else we're missing.

2024-01-16 18:14 UTC, shefalijoshi commented
> We can't merge this until we know consumers can still import it. I tested this with VIPER and it's totally borked, so likely (possibly?) a webpack configuration or something else we're missing.

OK I'll update with changes after investigation.

2024-01-17 20:44 UTC, unlikelyzero commented on package.json
> +    "test:e2e:watch": "npx playwright test --ui --config=./tests/e2e/playwright-quickstart.config.js",
driveby to write tests faster

2024-01-17 20:44 UTC, unlikelyzero commented on package.json
> -    "@deploysentinel/playwright": "0.3.4",
driveby

2024-01-17 20:44 UTC, unlikelyzero commented on package.json
> +    "eslint-plugin-import":"2.29.1",
make sure we didn't miss anything

2024-01-23 23:38 UTC, ozyx requested changes
I found a rogue `.only()`

2024-01-23 23:38 UTC, ozyx commented on tests/e2e/yamcs/network.e2e.spec.js
> +    test.only('Validate network traffic to YAMCS', async ({ page }) => {
`.only`

2024-01-23 23:38 UTC, ozyx commented on tests/e2e/yamcs/network.e2e.spec.js
> +        //I'm not sure what this block does yet
👁️

2024-01-24 10:47 UTC, scottbell requested changes

2024-01-24 10:47 UTC, scottbell commented on check-optional-dependencies.js
> +import fs from 'node:fs';
we should be using [fs/promises](https://nodejs.org/docs/latest-v18.x/api/fs.html#promise-example)

2024-01-24 10:47 UTC, scottbell commented on tests/e2e/yamcs/network.e2e.spec.js
> +        await new Promise(resolve => setTimeout(resolve, 500));
do we need this with the `waitForResponse` stuff?

2024-01-24 10:47 UTC, scottbell commented on tests/e2e/yamcs/network.e2e.spec.js
> +        await new Promise(resolve => setTimeout(resolve, 500));
same as above - is this still needed?

2024-01-24 20:42 UTC, merged