Add
akhenry/openmct-yamcs pull request #489
Opened 2024-12-18 09:28 UTC by scottbell

Closes #7936

### Describe your changes:

Adds event source and severity child objects under the Events object in YAMCS. Adds command queue child objects under the Commands objects in YAMCS.

### All Submissions:

* [ ] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [ ] Is this a [notable change](../docs/src/process/release.md) that will require a special callout in the release notes? For example, will this break compatibility with existing APIs or projects that consume these plugins?

### Author Checklist

* [ ] Changes address original issue?
* [ ] Tests included and/or updated with changes?
* [ ] Has this been smoke tested?
* [ ] Have you associated this PR with a `type:` label? Note: this is not necessarily the same as the original issue.
* [ ] Have you associated a milestone with this PR? Note: leave blank if unsure.
* [ ] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Reviewer has tested changes by following the provided instructions?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [ ] Code style and in-line documentation are appropriate?

2025-01-01 03:07 UTC, khalidadil commented on src/providers/events.js
> +    const eventSourceURL = `${url}/api/archive/${instance}/events/sources`;
I think this should be:
const eventSourceURL = `${url}api/archive/${instance}/events/sources`;

following the pattern of all the other constructed URLs that don't have a / after the ${url}

2025-01-01 03:09 UTC, khalidadil commented on src/providers/events.js
> +    return eventSourcesJson.sources;
The yamcs instance on viper ctrl returns results in the format of:
```
{
  "source": ["a", "b"]
}
```

so this would need to be `eventSourcesJson.source` for that format to work instead of `eventSourcesJson.sources`.

2025-01-06 08:37 UTC, scottbell commented on src/providers/events.js
> +    return eventSourcesJson.sources;
ah, this is [deprecated](https://docs.yamcs.org/yamcs-http-api/events/list-event-sources/). i'll check for both to support older versions of YAMCS

2025-02-17 21:08 UTC, shefalijoshi requested changes

2025-02-17 21:08 UTC, shefalijoshi commented on src/openmct-yamcs.js
> +            name: "Event",
This name `Event` should probably be different from the previous type.

2025-02-17 21:41 UTC, shefalijoshi requested changes

2025-02-17 21:41 UTC, shefalijoshi commented on src/providers/commands.js
> +                    hints: {
Need a comment here about the hint.

2025-03-05 19:08 UTC, shefalijoshi commented on src/providers/events.js
> +                    hints: {
Can you write some documentation on what this hint is and how it is used?
`hints: {
      label: 0
  }`

2025-03-05 19:08 UTC, shefalijoshi reviewed
Documentation request here.

2025-10-02 00:31 UTC, merged